### ISSUE TITLE
string must be compatible with Frosh\ThumbnailProcessor - height

### ISSUE THREAD

**Issue by csaeum** [FriendsOfShopware/FroshPlatformThumbnailProcessorImgProxy#1]
### PHP Version

8.0

### Shopware Version

6.4.11.1

### Actual behaviour

Establish compatibility with the plugin: https://github.com/FriendsOfShopware/FroshPlatformThumbnailProcessor

When installing, the following message appears:

"InternalServerError
Compile Error: Declaration of Frosh\ThumbnailProcessorImgProxy\Service\ThumbnailUrlTemplate::getUrl($mediaUrl, $mediaPath, $width): string must be compatible with Frosh\ThumbnailProcessor\Service\ThumbnailUrlTemplateInterface::getUrl(string $mediaUrl, string $mediaPath, string $width, string $height = ''): string"

### Expected behaviour

That it can be installed together with the processor plugin as both are dependent on each other.

### Steps to Reproduce?

Install thInstall the plugin after installing the latest processor plugine Plugin

**Comment by tinect** [comment]
This is for shopware 6 only.

**Comment by csaeum** [comment]
Yes, it is for Shopware 6 and it cannot be installed because it is dependent on the other plugins.

But if this is installed then it would be possible to install it if it didn't currently have incompatible places.

Please test again and confirm the bug

**Comment by tinect** [comment]
Oh. I'm sorry. 

Will try to check it later.
