### ISSUE TITLE
images are not loaded

### ISSUE THREAD

**Issue by brontius** [FriendsOfShopware/FroshPlatformThumbnailProcessorImgProxy#2]
### PHP Version

8.1.11

### Shopware Version

6.4.15.1

### Actual behaviour

images not found. 
After rewrite the path in ThumbnailUrlTemplate.php

$path = "/{$this->resizingType}/{$width}/{$height}/{$this->gravity}/{$this->enlarge}/{$encodedUrl}.{$extension}";
to
$path = "/rs:{$this->resizingType}:{$width}:{$height}/g:{$this->gravity}/{$encodedUrl}.{$extension}";

the images was loaded
Maybe it is not a bug, just wrong configuration of the imageServer. But all Docs what I have read sounds like a wrong path in that template. For the plugin I have not found  a detailed description. Maybe others help this . I hoping.

### Expected behaviour

load images

### Steps to Reproduce?

install new version of all on redhat

**Comment by tinect** [comment]
~~which version of imgproxy do you have?~~

EDIT: ahhh, it's the old and the new url-structure. will update the default soon.

**Comment by shyim** [comment]
@tinect can this be closed?
